name: Testing

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  pytest:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.7", "3.10"]
        torch-version: [1.11.0, 1.12.0]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PyTorch ${{ matrix.torch-version }}
        run: |
          pip install torch==${{ matrix.torch-version}}+cpu -f https://download.pytorch.org/whl/torch_stable.html

      - name: Install main package
        run: |
          # the -e/--editable flag is required otherwise the following error is raised:
          # ImportError: Could not find module '_version_cpu' in /home/runner/work/pytorch_scatter/pytorch_scatter/torch_scatter
          pip install -e .[test]

      - name: Run test-suite
        run: |
          pytest --cov --cov-report=xml

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        if: success()
        with:
          fail_ci_if_error: false
